# -*- coding: utf-8 -*-
"""SALES AND DATA VISUALIZATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYhqEpqoZmt-g1ixtgN39XAby3uEv0wH

## **SALES AND DATA VISUALIZATION**

### Data Loading
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sales = pd.read_csv("/content/Sales_Data.csv")
products = pd.read_csv("/content/Product_Master.csv")
customers = pd.read_csv("/content/Customer_Master.csv")
regions = pd.read_csv("/content/Region_Master.csv")

print(sales.head())

print(sales.info())

print(products.head())

"""### Data cleaning -- Check missing values"""

## Cleaned, transformed, and validated datasets using Python and Pandas
print(sales.isnull().sum())

print(products.isnull().sum())

print(customers.isnull().sum())

print(regions.isnull().sum())

"""### Check duplicates"""

print("Duplicate rows:", sales.duplicated().sum())

print(sales["Order_ID"].duplicated().sum())

print(customers["Customer_ID"].duplicated().sum())

print(products["Product_ID"].duplicated().sum())

"""## Convert dates"""

sales["Order_Date"] = pd.to_datetime(sales["Order_Date"])
sales["Ship_Date"] = pd.to_datetime(sales["Ship_Date"])

sales["Order_Year"] = sales["Order_Date"].dt.year
sales["Order_Month"] = sales["Order_Date"].dt.month
sales["Month_Name"] = sales["Order_Date"].dt.month_name()

sales["Shipping_Days"] = (
    sales["Ship_Date"] - sales["Order_Date"]
).dt.days

"""## Validate calculations"""

sales["Calculated_Gross_Sales"] = (
    sales["Quantity"] * sales["Unit_Price"]
)

difference = (
    sales["Calculated_Gross_Sales"] -
    sales["Gross_Sales"]
)

print(difference.abs().max())

"""## Validate discount"""

sales["Calculated_Discount"] = (
    sales["Gross_Sales"] *
    sales["Discount_Pct"]
)

sales['Discount_Amount']

"""## Validate Net Sales"""

sales["Calculated_Net_Sales"] = (
    sales["Gross_Sales"] -
    sales["Discount_Amount"]
)

sales["Net_Sales"]

"""## Validate Profit"""

sales["Calculated_Profit"] = (
    sales["Net_Sales"] -
    sales["Cost"] +
    sales["Shipping_Fee"]
)

sales["Profit"]

"""## Create business KPIs"""

## Total Revenue
total_revenue = sales["Net_Sales"].sum()
print(total_revenue)

## Total Profit
total_profit = sales["Profit"].sum()
print(total_profit)

## Total Quantity
total_quantity = sales["Quantity"].sum()
print(total_quantity)

## Number of Orders
total_orders = sales["Order_ID"].nunique()
print(total_orders)

## Average Order Value
aov = total_revenue / total_orders
print(aov)

## Profit Margin
profit_margin = (
    total_profit / total_revenue
) * 100

print(profit_margin)

"""## Product analysis"""

## analyze products
product_sales = (
    sales.groupby("Product_Name")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum"),
        Quantity=("Quantity", "sum")
    )
    .sort_values("Revenue", ascending=False)
)

print(product_sales.head(10))

## top 10 products
top_products = product_sales.head(10)

top_products["Revenue"].plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Top 10 Products by Revenue")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## Category analysis

"""

category_analysis = (
    sales.groupby("Category")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum"),
        Quantity=("Quantity", "sum")
    )
    .sort_values("Revenue", ascending=False)
)

print(category_analysis)

## Calculating margin
category_analysis["Profit_Margin"] = (
    category_analysis["Profit"] /
    category_analysis["Revenue"]
) * 100

"""## Regional analysis"""

region_analysis = (
    sales.groupby("Region")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum"),
        Quantity=("Quantity", "sum")
    )
)

region_analysis["Profit_Margin"] = (
    region_analysis["Profit"] /
    region_analysis["Revenue"]
) * 100

print(region_analysis)

## state-level analysis
state_analysis = (
    sales.groupby("State")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique")
    )
    .sort_values("Revenue", ascending=False)
)

print(state_analysis)

"""## Time-series analysis"""

## monthly sales
monthly_sales = (
    sales.groupby(
        sales["Order_Date"].dt.to_period("M")
    )
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum")
    )
)

print(monthly_sales)

monthly_sales["Revenue"].plot(
    figsize=(12,6)
)

plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.tight_layout()
plt.show()

"""## Channel analysis"""

channel_analysis = (
    sales.groupby("Channel")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique")
    )
)

print(channel_analysis)

channel_analysis["Profit_Margin"] = (
    channel_analysis["Profit"] /
    channel_analysis["Revenue"]
) * 100

"""## Customer analysis"""

## Merging customer information
customer_sales = sales.merge(
    customers,
    on="Customer_ID",
    how="left",
    suffixes=("", "_Master")
)

segment_analysis = (
    customer_sales.groupby("Customer_Segment")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique")
    )
)

print(segment_analysis)

## Analyze age group
age_analysis = (
    customer_sales.groupby("Age_Group")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Orders=("Order_ID", "nunique")
    )
)

print(age_analysis)

"""## Order status analysis"""

status_analysis = (
    sales.groupby("Order_Status")
    .agg(
        Orders=("Order_ID", "nunique"),
        Revenue=("Net_Sales", "sum")
    )
)

print(status_analysis)

status_analysis["Order_Percentage"] = (
    status_analysis["Orders"] /
    status_analysis["Orders"].sum()
) * 100

"""## Discount analysis"""

discount_analysis = (
    sales.groupby("Discount_Pct")
    .agg(
        Revenue=("Net_Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique")
    )
)

print(discount_analysis)

